---
- name: Check if "{{ tails_config_securedrop_admin_dotfiles }}" is a directory
  stat:
    path: "{{ tails_config_securedrop_admin_dotfiles }}"
  register: admin_dotfiles_stat

- debug:
    var: admin_dotfiles_stat

- name: Ensure "{{ tails_config_live_dotfiles }}/.securedrop-admin" directory exists
  file:
    path: "{{ tails_config_live_dotfiles }}/.securedrop-admin"
    state: directory
    mode: "0755"
    owner: amnesia
    group: amnesia

- name: Copy existing "{{ tails_config_securedrop_admin_dotfiles }}/*" to live dotfiles if it is a directory
  copy:
    src: "{{ tails_config_securedrop_admin_dotfiles }}/"
    dest: "{{ tails_config_live_dotfiles }}/.securedrop-admin/"
  when: admin_dotfiles_stat.stat.isdir

- name: Remove "{{ tails_config_securedrop_admin_dotfiles }}" if it exists
  file:
    path: "{{ tails_config_securedrop_admin_dotfiles }}"
    state: absent

- name: Ensure "{{ tails_config_securedrop_admin_dotfiles }}" is a symlink to live dotfiles
  file:
    src: "{{ tails_config_live_dotfiles }}/.securedrop-admin"
    dest: "{{ tails_config_securedrop_admin_dotfiles }}"
    state: link
    owner: amnesia
