---
- name: Check if "{{ tails_config_securedrop_admin_dotfiles }}" is a directory
  stat:
    path: "{{ tails_config_securedrop_admin_dotfiles }}"
  register: admin_dotfiles_stat

- name: Move existing "{{ tails_config_securedrop_admin_dotfiles }}" to live dotfiles if it is a directory
  command: mv "{{ tails_config_securedrop_admin_dotfiles }}" "{{ tails_config_live_dotfiles }}/.securedrop-admin"
  when: admin_dotfiles_stat.stat.isdir
  args:
    removes: "{{ tails_config_securedrop_admin_dotfiles }}"
    creates: "{{ tails_config_live_dotfiles }}/.securedrop-admin"

- name: Ensure "{{ tails_config_live_dotfiles }}/.securedrop-admin" directory exists
  file:
    path: "{{ tails_config_live_dotfiles }}/.securedrop-admin"
    state: directory
    mode: "0755"
    owner: amnesia
    group: amnesia

- name: Remove "{{ tails_config_securedrop_admin_dotfiles }}" if it exists and is not a symlink
  file:
    path: "{{ tails_config_securedrop_admin_dotfiles }}"
    state: absent
  when: admin_dotfiles_stat.stat.exists and not admin_dotfiles_stat.stat.islnk

- name: Ensure "{{ tails_config_securedrop_admin_dotfiles }}" is a symlink to live dotfiles
  file:
    src: "{{ tails_config_live_dotfiles }}/.securedrop-admin"
    dest: "{{ tails_config_securedrop_admin_dotfiles }}"
    state: link
    owner: amnesia
