---
name: Publish Demo Landing Page

on:
  push:
    branches: ["develop"]
    paths:
    - devops/demo/landing-page/**

jobs:
  build:
    name: Build Landing Page
    uses: freedomofpress/actionslib/.github/workflows/oci-build.yaml@main
    permissions:
      contents: read
      actions: read
      packages: write
    with:
      context: "."
      containerfile: devops/demo/landing-page/Dockerfile
      registry: ghcr.io/freedomofpress/securedrop-demo-landing-page
      add-branch-tags: true
    secrets:
      registry-password: ${{ secrets.GITHUB_TOKEN }}

  notify:
    uses: freedomofpress/actionslib/.github/workflows/update-k8s-trigger.yaml@main
    needs:
    - build
    if: ${{ needs.build.result == 'success' }}
    permissions:
      contents: read
      actions: read
      pull-requests: read
    with:
      trigger: sdo-demo/production-landing-page
      sha: ${{ github.sha }}
    secrets:
      local-token: ${{ secrets.GITHUB_TOKEN }}
      k8s-configs-token: ${{ secrets.K8S_CONFIGS_GITHUB_TOKEN }}
